# Generated by Django 4.0.1 on 2022-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='author_about',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='author_image',
            field=models.CharField(default='Null', max_length=2000),
        ),
        migrations.AddField(
            model_name='home',
            name='bg_image',
            field=models.CharField(default='Null', max_length=2000),
        ),
    ]
