# Generated by Django 4.0.1 on 2022-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_home_author_about_home_author_image_home_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_detail', models.CharField(default='Null', max_length=1000)),
                ('page_image', models.CharField(default='Null', max_length=2000)),
                ('bg_image', models.CharField(default='Null', max_length=2000)),
            ],
        ),
    ]
