# Generated by Django 4.0.1 on 2022-04-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_author_detail_about_author_detail1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='author_detail7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
