# Generated by Django 4.0.1 on 2022-04-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_about_author_detail7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='author_detail10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='author_detail8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='author_detail9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='bg_image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='page_image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
