# Generated by Django 4.0.1 on 2022-04-23 12:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_about_author_detail10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_resume', models.CharField(default='Null', max_length=2000)),
                ('bg_image', models.CharField(default='Null', max_length=2000)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
