# Generated by Django 4.0.1 on 2022-04-23 14:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_resume_author_resume_resume_author_resume1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_link', models.CharField(blank=True, default='Null', max_length=500)),
                ('project_image', models.CharField(blank=True, default='Null', max_length=2000)),
                ('project_head1', models.CharField(blank=True, default='Null', max_length=200)),
                ('project_head2', models.CharField(blank=True, default='Null', max_length=200)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
