# Generated by Django 4.0.1 on 2022-04-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_project_link_project_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(blank=True, default='Null', max_length=500)),
                ('name', models.CharField(blank=True, default='Null', max_length=200)),
                ('email', models.CharField(blank=True, default='Null', max_length=200)),
                ('subject', models.CharField(blank=True, default='Null', max_length=200)),
                ('message', models.TextField(blank=True, default='Null')),
            ],
        ),
    ]
