# Generated by Django 4.0.1 on 2022-04-26 04:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_contact_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(blank=True, default='Null', max_length=500)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='map',
        ),
    ]
