# Generated by Django 4.0.1 on 2022-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_map_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_image',
            field=models.CharField(blank=True, default='Null', max_length=2000),
        ),
    ]
