# Generated by Django 4.0.1 on 2022-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_resume_experience_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_experience',
            name='bg_image',
            field=models.CharField(default='Null', max_length=2000),
        ),
    ]
