# Generated by Django 4.0.1 on 2022-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_resume_experience_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_experience',
            name='from_year',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='resume_experience',
            name='to_year',
            field=models.IntegerField(default='0'),
        ),
    ]
